### ISSUE TITLE
in lead detail remove optional("") from being displayed

### ISSUE THREAD

**Issue by ryandhubbard** [ryandhubbard/IDX_Broker_iOS#51]

**Comment by Aaron-O** [comment]
The simplest fix I can see is adding this to the end of init(leadDict: NSDictionary) section of leadsClass.swift

            // Removes "Optional(\""\)" from city
            if city?.range(of: "Optional") != nil {
                city = city?.replacingOccurrences(of: "Optional(\"", with: "")
                city = city?.replacingOccurrences(of: "\")", with: "")
            }
