### ISSUE TITLE
Keyboard does not always dismiss

### ISSUE THREAD

**Issue by ryandhubbard** [ryandhubbard/IDX_Broker_iOS#52]

**Comment by Aaron-O** [comment]
What steps lead up to this error?  I tried in the "create new leads" but wasn't able replicate.

**Comment by ryandhubbard** [comment]
@Aaron-O  if you test this on your phone you get a real keyboard doesnt apply in the simulator 
But this happens in the search bars for the dashboards and the new lead when [return, search, or done] in the keyboard is pressed it should close the keyboard
