### ISSUE TITLE
App will not go past the enter API key page

### ISSUE THREAD

**Issue by sfgarza** [ryandhubbard/IDX_Broker_iOS#81]
Device: iPhone 5s (iOS 11.0.1)
Issue: Nothing happens when I enter the API key and press continue. No error messages seem to be thrown even when I enter an invalid key.

**Comment by ryandhubbard** [comment]
@sfgarza I am having trouble replicating this issue. 
Did it change pages when you pressed continue or did it just stay on the front page
Is the continue on the page or the keyboard?
Try pressing Enter On the page
![img_0407](https://user-images.githubusercontent.com/935207/31139547-c3500d18-a826-11e7-9f8a-7e4a17342ebc.PNG)

**Comment by sfgarza** [comment]
There is no Enter button on my screen. When I hit continue on the keyboard it doesnt do anything at all. 
![idxforza-scrren](https://user-images.githubusercontent.com/8662253/31161982-885caeb4-a88f-11e7-9ae4-de3f906a6f90.png)
